//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public string spec_name { get; set; }
        public bool purpose { get; set; }
        public System.DateTime d_renovation { get; set; }
        public System.DateTime d_expiration { get; set; }
        public string license_fee { get; set; }
        public string payer { get; set; }
        public string license_type { get; set; }
        public string seller { get; set; }
        public string owner { get; set; }
        public string req_faculty { get; set; }
        public string req_personnel { get; set; }
        public string users { get; set; }
        public string explanation { get; set; }
        public bool active { get; set; }
    }
}
